TEMPLATE_NAME_KEY = "template_name"
PARAMETER_KEYS_KEY = "parameter_keys"
PARAMETER_OVERRIDES_KEY = "parameter_overrides"
PIPELINES_KEY = "pipelines"

SNAPSHOT_ID_OVERRIDE_KEY = "SnapshotID"
BUILD_TOOLS_ACCOUNT_ID_OVERRIDE_KEY = "BuildToolsAccountId"
PROOF_ACCOUNT_ID_TO_ADD_KEY = "ProofAccountIdToAdd"
BUILD_TOOLS_SNAPSHOT_ID_KEY = "build-tools-image-id"
SHARED_BUCKET_PARAM_KEY = "SharedToolsS3Bucket"
