#!/usr/bin/env python3

# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import argparse

import botocore_amazon.monkeypatch
import boto3

import secretst

def create_parser():
    arg = argparse.ArgumentParser(
        description='Get AWS stack output values.'
    )

    arg.add_argument('--profile',
                     metavar='NAME',
                     help='AWS account profile name'
                    )
    arg.add_argument('--secretid',
                     metavar='ID',
                     help='AWS secret id'
                    )
    return arg

def main():
    args = create_parser().parse_args()

    session = boto3.session.Session(profile_name=args.profile)
    secrets = secretst.Secrets(session)

    (_, value) = secrets.get_secret_value(args.secretid)
    print(value)

if __name__ == '__main__':
    main()
